name: CI

on:
  - push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install Dependencies - root
        run: npm install
      - name: Install Dependencies - client
        run: npm install
        working-directory: client
      - name: Check Client Lint
        run: npm run lint:es
        working-directory: client
      - name: Install Dependencies - server
        run: npm install
        working-directory: server
      - name: Check Server Lint
        run: npm run lint:es
        working-directory: server

  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install Dependencies - root
        run: npm install
      - name: Type Check - client
        run: npm run check-types:client
      - name: Type Check - server
        run: npm run check-types:server
      - name: Install Dependencies - client
        run: npm install
        working-directory: client
      - name: Check Client Test
        run: npm run test
        working-directory: client
      - name: Install Dependencies - server
        run: npm install
        working-directory: server
      - name: Check Server Test
        run: npm run test
        working-directory: server
        
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install Dependencies - client
        run: npm install
        working-directory: client
      - name: Build JS And CSS
        run: npm run client:prod